name: "build"
on: push
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@70742d22d932888bb199587f910c72183e62c6da
    - name: "nix-build"
      run: nix-build --max-jobs 1
